### PR TITLE
add modules and loose options

### PR DESCRIPTION
**Pull request by ngryman**
Heavily inspired from https://github.com/babel/babel/blob/master/packages/babel-preset-es2015.

I tested by npm linking locally to one of my project and it works for me. You can do additional tests if you want.

### CODE REVIEW

**Comment by leebenson** [comment]
Thanks @ngryman, much appreciated

**Comment by ngryman** [comment]
Could you release a new version including this patch?
I need this quite urgently.

Thanks 👊

**Comment by leebenson** [comment]
I'll get this bumped tonight. Out of the office currently. In the meantime, you should be able to ref the git repo directly in npm and switch when it's bumped.

**Comment by ngryman** [comment]
Yes that's what I've done 👍

**Comment by leebenson** [comment]
@ngryman - pushed to NPM as version 12.0.0

**Comment by ngryman** [comment]
Awesome thanks!

**Pull request merged**
